// EdgeLeak — Public client config
// SAFE to expose: Supabase publishable key, Stripe price IDs.
// SECRETS (sb_secret_*, sk_live_*) live ONLY in Vercel env vars.

window.SUPABASE_URL = 'https://uqeqbjkgfsmqjakuotfy.supabase.co';
window.SUPABASE_ANON_KEY = 'sb_publishable_BWii913uFJLpQNvIuu0tCQ_NrRPp2x_';

// Stripe price IDs (Live mode)
window.STRIPE_PRICE_HOBBYIST         = 'price_1TS99LLqC6EEycUgKIGUwTwL'; // €3.99/mo
window.STRIPE_PRICE_REGULAR          = 'price_1TRg2nLqC6EEycUgd0TXBiua'; // €9.99/mo
window.STRIPE_PRICE_HOBBYIST_ANNUAL  = 'price_1TTOHULqC6EEycUgvrfcibrH'; // €38/year (-21%)
window.STRIPE_PRICE_REGULAR_ANNUAL   = 'price_1TTOHXLqC6EEycUgMeZAQjX3'; // €96/year (-20%)
window.TRIAL_DAYS = 14; // 14-day free trial on all paid plans

// Plan capabilities (kept client-side for paywall checks; truth lives in Supabase via webhook)
window.PLANS = {
  free: {
    name: 'Apprentice',
    positions: ['BTN','CO','BB'],
    stacks: ['100'],
    situations: ['open','vs-open','vs-3bet'],
    maxSaves: 3,
    canExport: false,
  },
  hobbyist: {
    name: 'Hobbyist',
    positions: ['UTG','UTG+1','LJ','HJ','CO','BTN','SB','BB'],
    stacks: ['100','40'],
    situations: ['open','vs-open','vs-3bet'],
    maxSaves: 25,
    canExport: true,
  },
  regular: {
    name: 'Regular',
    positions: ['UTG','UTG+1','LJ','HJ','CO','BTN','SB','BB'],
    stacks: ['100','40','20'],
    situations: ['open','vs-open','vs-3bet'],
    maxSaves: 9999,
    canExport: true,
  },
};

// Internationalization (FR/EN)
window.I18N = {
  fr: {
    // Nav
    'nav.ranges': 'Ranges',
    'nav.howItWorks': 'Comment ça marche',
    'nav.pricing': 'Tarifs',
    'nav.faq': 'FAQ',
    'nav.signin': 'Se connecter',
    'nav.startFree': 'Démarrer gratuitement →',
    // Hero
    'hero.eyebrow': 'Ranges GTO · Construit pour les joueurs sérieux',
    'hero.h1.a': 'Une bibliothèque',
    'hero.h1.b': 'de ',
    'hero.h1.solutions': 'solutions',
    'hero.h1.c': ',',
    'hero.h1.d': 'instantanément ',
    'hero.h1.browsable': 'consultable.',
    'hero.sub': 'Ranges pré-résolues pour chaque position, chaque profondeur de tapis, chaque spot courant — recherchables, filtrables, color-codées par fréquence. Arrête de deviner. Commence à savoir.',
    'hero.cta1': 'Démarrer gratuitement →',
    'hero.cta2': 'Voir en action',
    'hero.note': 'Sans carte bancaire · Annule à tout moment · Made in Paris',
    // Sections
    'section.library.badge': '01 — La bibliothèque',
    'section.library.titleA': 'Chaque spot,',
    'section.library.titleB': 'résolu & visualisé.',
    'section.library.sub': 'Ouvre la matrice pour n\'importe quelle position, profondeur, situation. Color-codée par fréquence GTO. Plus de doutes à la table — ni en study.',
    // Pricing
    'pricing.badge': 'Tarifs · 2026',
    'pricing.titleA': 'Trois plans.',
    'pricing.titleB': 'Aucun upsell.',
    'pricing.sub': 'Paie pour les ranges, pas pour le superflu. Annule n\'importe quand — garde tes ranges sauvegardées.',
    'pricing.free.tag': '',
    'pricing.free.name': 'Apprentice',
    'pricing.free.desc': 'Pour tes premières sessions d\'étude.',
    'pricing.free.price': 'Gratuit',
    'pricing.free.period': 'Pour toujours',
    'pricing.free.cta': 'Démarrer gratuitement →',
    'pricing.hobbyist.tag': 'Populaire',
    'pricing.hobbyist.name': 'Hobbyist',
    'pricing.hobbyist.desc': 'Pour le joueur sérieux qui monte en stakes.',
    'pricing.hobbyist.price': '3,99€',
    'pricing.hobbyist.period': 'par mois · annule à tout moment',
    'pricing.hobbyist.cta': 'Choisir Hobbyist →',
    'pricing.regular.tag': 'Plus populaire',
    'pricing.regular.name': 'Regular',
    'pricing.regular.desc': 'Le grinder discipliné qui ne loupe rien.',
    'pricing.regular.price': '9,99€',
    'pricing.regular.period': 'par mois · annule à tout moment',
    'pricing.regular.cta': 'Choisir Regular →',
    // FAQ
    'faq.title': 'Questions, ',
    'faq.title2': 'réponses.',
    // Onboarding
    'onb.title.a': 'Commence ta ',
    'onb.title.italic': 'pratique',
    'onb.title.b': ' silencieuse.',
    'onb.sub': 'Quatre étapes. Cinq minutes. À la fin, EdgeLeak en saura assez sur ton jeu pour repérer tes leaks ce soir.',
    'onb.step': 'Étape',
    'onb.of': 'sur',
    'onb.continue': 'Continuer →',
    'onb.optional': 'Optionnel · Passer →',
    'onb.back': 'Retour',
    'onb.s1.eyebrow': '· Présentations',
    'onb.s1.title.a': 'D\'abord, ',
    'onb.s1.title.italic': 'présentons-nous',
    'onb.s1.title.b': '.',
    'onb.s1.sub': 'On utilisera ton prénom pour personnaliser ton tableau de bord.',
    'onb.s1.name': 'PRÉNOM',
    'onb.s1.email': 'EMAIL',
    'onb.s1.pass': 'MOT DE PASSE',
    'onb.s1.checkbox': 'Envoie-moi un récap hebdo de mon jeu — le dimanche, en clair.',
    'onb.s2.eyebrow': '· Ton jeu',
    'onb.s2.title.a': 'Tu joues à ',
    'onb.s2.title.italic': 'quoi',
    'onb.s2.title.b': ' ?',
    'onb.s2.sub': 'Sélectionne tout ce qui s\'applique. On adaptera ton tableau de bord en conséquence.',
    'onb.s2.opt1': 'Cash game deep stack, no clock',
    'onb.s2.opt2': 'MTT — ICM, bubble, finals',
    'onb.s2.opt3': 'Heads-up, hyper-turbo',
    'onb.s2.opt4': 'PLO — 4-card omaha (bientôt)',
    'onb.s3.eyebrow': '· Tes stakes',
    'onb.s3.title.a': 'Où est-ce que tu ',
    'onb.s3.title.italic': 'joues',
    'onb.s3.title.b': ' ?',
    'onb.s3.sub': 'On calibrera les ranges et les seuils de bankroll à ton buy-in habituel.',
    'onb.s3.bankroll': 'BANKROLL SUGGÉRÉE',
    'onb.s3.bankrollNote': '50-100 buy-ins · variance standard',
    'onb.s4.eyebrow': '· Ton objectif',
    'onb.s4.title.a': 'À quoi ressemble ',
    'onb.s4.title.italic': 'gagner',
    'onb.s4.title.b': ' pour toi ?',
    'onb.s4.sub': 'Choisis ton étoile polaire. On affichera ta progression face à elle.',
    'onb.s4.opt1': 'Reg confirmé. Volume avant tout.',
    'onb.s4.opt2': 'Je veux passer de NL100 à NL500 cette année.',
    'onb.s4.opt3': 'Plein temps. Croissance bankroll au-dessus de tout.',
    'onb.s4.opt4': 'Rester break-even ou mieux. Tout tracker.',
    'onb.finish': 'Entrer dans EdgeLeak →',
  },
  en: {
    'nav.ranges': 'Ranges',
    'nav.howItWorks': 'How it works',
    'nav.pricing': 'Pricing',
    'nav.faq': 'FAQ',
    'nav.signin': 'Sign in',
    'nav.startFree': 'Start free →',
    'hero.eyebrow': 'GTO Ranges · Built for serious players',
    'hero.h1.a': 'A library',
    'hero.h1.b': 'of ',
    'hero.h1.solutions': 'solutions',
    'hero.h1.c': ',',
    'hero.h1.d': 'instantly ',
    'hero.h1.browsable': 'browsable.',
    'hero.sub': 'Pre-solved ranges for every position, every stack depth, every common spot — searchable, filterable, color-coded by frequency. Stop wondering. Start knowing.',
    'hero.cta1': 'Start free →',
    'hero.cta2': 'See it in action',
    'hero.note': 'No credit card · Cancel anytime · Built in Paris',
    'section.library.badge': '01 — The library',
    'section.library.titleA': 'Every spot,',
    'section.library.titleB': 'solved & visualised.',
    'section.library.sub': 'Open the matrix for any position, any stack depth, any common situation. Color-coded by GTO frequency. No more guessing — at the table or in your study.',
    'pricing.badge': 'Pricing · 2026',
    'pricing.titleA': 'Three plans.',
    'pricing.titleB': 'No upsells.',
    'pricing.sub': 'Pay for the ranges, not the chrome. Cancel any month — keep your saved ranges with you.',
    'pricing.free.tag': '',
    'pricing.free.name': 'Apprentice',
    'pricing.free.desc': 'For your first study sessions.',
    'pricing.free.price': 'Free',
    'pricing.free.period': 'Forever',
    'pricing.free.cta': 'Start free →',
    'pricing.hobbyist.tag': 'Popular',
    'pricing.hobbyist.name': 'Hobbyist',
    'pricing.hobbyist.desc': 'For the serious player moving up stakes.',
    'pricing.hobbyist.price': '€3.99',
    'pricing.hobbyist.period': 'per month · cancel anytime',
    'pricing.hobbyist.cta': 'Pick Hobbyist →',
    'pricing.regular.tag': 'Most chosen',
    'pricing.regular.name': 'Regular',
    'pricing.regular.desc': 'The disciplined grinder. Misses nothing.',
    'pricing.regular.price': '€9.99',
    'pricing.regular.period': 'per month · cancel anytime',
    'pricing.regular.cta': 'Pick Regular →',
    'faq.title': 'Questions, ',
    'faq.title2': 'answered.',
    'onb.title.a': 'Begin your ',
    'onb.title.italic': 'quiet',
    'onb.title.b': ' practice.',
    'onb.sub': 'Four steps. Five minutes. By the end, EdgeLeak will know enough about your game to start spotting the leaks tonight.',
    'onb.step': 'Step',
    'onb.of': 'of',
    'onb.continue': 'Continue →',
    'onb.optional': 'Optional · Skip →',
    'onb.back': 'Back',
    'onb.s1.eyebrow': '· Tell us your name',
    'onb.s1.title.a': 'First, the ',
    'onb.s1.title.italic': 'introductions',
    'onb.s1.title.b': '.',
    'onb.s1.sub': 'We\'ll use your first name on your dashboard. Nothing more.',
    'onb.s1.name': 'DISPLAY NAME',
    'onb.s1.email': 'EMAIL',
    'onb.s1.pass': 'PASSWORD',
    'onb.s1.checkbox': 'Send me a weekly review of my game — Sundays, in plain language.',
    'onb.s2.eyebrow': '· Your game',
    'onb.s2.title.a': 'What do you ',
    'onb.s2.title.italic': 'play',
    'onb.s2.title.b': '?',
    'onb.s2.sub': 'Pick all that apply. We\'ll tune your dashboard accordingly.',
    'onb.s2.opt1': 'Cash deep stack, no clock',
    'onb.s2.opt2': 'MTT — ICM, bubble play, finals',
    'onb.s2.opt3': 'Heads-up, hyper-turbo',
    'onb.s2.opt4': 'PLO — 4-card omaha (beta)',
    'onb.s3.eyebrow': '· Your stakes',
    'onb.s3.title.a': 'Where do you ',
    'onb.s3.title.italic': 'sit down',
    'onb.s3.title.b': '?',
    'onb.s3.sub': 'We\'ll calibrate ranges and bankroll thresholds to your usual buy-in.',
    'onb.s3.bankroll': 'SUGGESTED BANKROLL',
    'onb.s3.bankrollNote': '50-100 buy-ins · standard variance',
    'onb.s4.eyebrow': '· Your goal',
    'onb.s4.title.a': 'What would ',
    'onb.s4.title.italic': 'winning',
    'onb.s4.title.b': ' look like?',
    'onb.s4.sub': 'Pick a north star. We\'ll show progress against it on your dashboard.',
    'onb.s4.opt1': 'Confirmed reg. Volume above all.',
    'onb.s4.opt2': 'I want to graduate from NL100 to NL500 this year.',
    'onb.s4.opt3': 'Full-time. Bankroll growth above all.',
    'onb.s4.opt4': 'Stay break-even or better. Track everything.',
    'onb.finish': 'Enter EdgeLeak →',
  }
};

// Translation helper
window.t = function(key, lang){
  const L = lang || localStorage.getItem('el_lang') || 'fr';
  return (window.I18N[L] && window.I18N[L][key]) || (window.I18N['en'][key]) || key;
};
